/**

Generated by the following Solidity interface...
```solidity
interface IFraxEtherRedemptionQueue {
    function burnRedemptionTicketNft(uint256 _nftId, address payable _recipient) external;
    function enterRedemptionQueueViaSfrxEth(address _recipient, uint120 _sfrxEthAmount) external returns (uint256 _nftId);
    function redemptionQueueState() external view returns (uint64 nextNftId, uint64 queueLengthSecs, uint64 redemptionFee, uint64 earlyExitFee);
}
```

...which was generated by the following JSON ABI:
```json
[
  {
    "type": "function",
    "name": "burnRedemptionTicketNft",
    "inputs": [
      {
        "name": "_nftId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "_recipient",
        "type": "address",
        "internalType": "address payable"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "enterRedemptionQueueViaSfrxEth",
    "inputs": [
      {
        "name": "_recipient",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_sfrxEthAmount",
        "type": "uint120",
        "internalType": "uint120"
      }
    ],
    "outputs": [
      {
        "name": "_nftId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "redemptionQueueState",
    "inputs": [],
    "outputs": [
      {
        "name": "nextNftId",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "queueLengthSecs",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "redemptionFee",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "earlyExitFee",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  }
]
```*/
#[allow(
    non_camel_case_types,
    non_snake_case,
    clippy::pub_underscore_fields,
    clippy::style,
    clippy::empty_structs_with_brackets
)]
pub mod IFraxEtherRedemptionQueue {
    use super::*;
    use alloy::sol_types as alloy_sol_types;
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    /**Function with signature `burnRedemptionTicketNft(uint256,address)` and selector `0x0a5334e5`.
```solidity
function burnRedemptionTicketNft(uint256 _nftId, address _recipient) external;
```*/
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct burnRedemptionTicketNftCall {
        #[allow(missing_docs)]
        pub _nftId: alloy::sol_types::private::primitives::aliases::U256,
        #[allow(missing_docs)]
        pub _recipient: alloy::sol_types::private::Address,
    }
    ///Container type for the return parameters of the [`burnRedemptionTicketNft(uint256,address)`](burnRedemptionTicketNftCall) function.
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct burnRedemptionTicketNftReturn {}
    #[allow(
        non_camel_case_types,
        non_snake_case,
        clippy::pub_underscore_fields,
        clippy::style
    )]
    const _: () = {
        use alloy::sol_types as alloy_sol_types;
        {
            #[doc(hidden)]
            #[allow(dead_code)]
            type UnderlyingSolTuple<'a> = (
                alloy::sol_types::sol_data::Uint<256>,
                alloy::sol_types::sol_data::Address,
            );
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (
                alloy::sol_types::private::primitives::aliases::U256,
                alloy::sol_types::private::Address,
            );
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<burnRedemptionTicketNftCall>
            for UnderlyingRustTuple<'_> {
                fn from(value: burnRedemptionTicketNftCall) -> Self {
                    (value._nftId, value._recipient)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>>
            for burnRedemptionTicketNftCall {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self {
                        _nftId: tuple.0,
                        _recipient: tuple.1,
                    }
                }
            }
        }
        {
            #[doc(hidden)]
            #[allow(dead_code)]
            type UnderlyingSolTuple<'a> = ();
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = ();
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<burnRedemptionTicketNftReturn>
            for UnderlyingRustTuple<'_> {
                fn from(value: burnRedemptionTicketNftReturn) -> Self {
                    ()
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>>
            for burnRedemptionTicketNftReturn {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self {}
                }
            }
        }
        impl burnRedemptionTicketNftReturn {
            fn _tokenize(
                &self,
            ) -> <burnRedemptionTicketNftCall as alloy_sol_types::SolCall>::ReturnToken<
                '_,
            > {
                ()
            }
        }
        #[automatically_derived]
        impl alloy_sol_types::SolCall for burnRedemptionTicketNftCall {
            type Parameters<'a> = (
                alloy::sol_types::sol_data::Uint<256>,
                alloy::sol_types::sol_data::Address,
            );
            type Token<'a> = <Self::Parameters<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            type Return = burnRedemptionTicketNftReturn;
            type ReturnTuple<'a> = ();
            type ReturnToken<'a> = <Self::ReturnTuple<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            const SIGNATURE: &'static str = "burnRedemptionTicketNft(uint256,address)";
            const SELECTOR: [u8; 4] = [10u8, 83u8, 52u8, 229u8];
            #[inline]
            fn new<'a>(
                tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType,
            ) -> Self {
                tuple.into()
            }
            #[inline]
            fn tokenize(&self) -> Self::Token<'_> {
                (
                    <alloy::sol_types::sol_data::Uint<
                        256,
                    > as alloy_sol_types::SolType>::tokenize(&self._nftId),
                    <alloy::sol_types::sol_data::Address as alloy_sol_types::SolType>::tokenize(
                        &self._recipient,
                    ),
                )
            }
            #[inline]
            fn tokenize_returns(ret: &Self::Return) -> Self::ReturnToken<'_> {
                burnRedemptionTicketNftReturn::_tokenize(ret)
            }
            #[inline]
            fn abi_decode_returns(data: &[u8]) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence(data)
                    .map(Into::into)
            }
            #[inline]
            fn abi_decode_returns_validate(
                data: &[u8],
            ) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence_validate(data)
                    .map(Into::into)
            }
        }
    };
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    /**Function with signature `enterRedemptionQueueViaSfrxEth(address,uint120)` and selector `0xe14cbb8a`.
```solidity
function enterRedemptionQueueViaSfrxEth(address _recipient, uint120 _sfrxEthAmount) external returns (uint256 _nftId);
```*/
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct enterRedemptionQueueViaSfrxEthCall {
        #[allow(missing_docs)]
        pub _recipient: alloy::sol_types::private::Address,
        #[allow(missing_docs)]
        pub _sfrxEthAmount: alloy::sol_types::private::primitives::aliases::U120,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    ///Container type for the return parameters of the [`enterRedemptionQueueViaSfrxEth(address,uint120)`](enterRedemptionQueueViaSfrxEthCall) function.
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct enterRedemptionQueueViaSfrxEthReturn {
        #[allow(missing_docs)]
        pub _nftId: alloy::sol_types::private::primitives::aliases::U256,
    }
    #[allow(
        non_camel_case_types,
        non_snake_case,
        clippy::pub_underscore_fields,
        clippy::style
    )]
    const _: () = {
        use alloy::sol_types as alloy_sol_types;
        {
            #[doc(hidden)]
            #[allow(dead_code)]
            type UnderlyingSolTuple<'a> = (
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Uint<120>,
            );
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (
                alloy::sol_types::private::Address,
                alloy::sol_types::private::primitives::aliases::U120,
            );
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<enterRedemptionQueueViaSfrxEthCall>
            for UnderlyingRustTuple<'_> {
                fn from(value: enterRedemptionQueueViaSfrxEthCall) -> Self {
                    (value._recipient, value._sfrxEthAmount)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>>
            for enterRedemptionQueueViaSfrxEthCall {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self {
                        _recipient: tuple.0,
                        _sfrxEthAmount: tuple.1,
                    }
                }
            }
        }
        {
            #[doc(hidden)]
            #[allow(dead_code)]
            type UnderlyingSolTuple<'a> = (alloy::sol_types::sol_data::Uint<256>,);
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (
                alloy::sol_types::private::primitives::aliases::U256,
            );
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<enterRedemptionQueueViaSfrxEthReturn>
            for UnderlyingRustTuple<'_> {
                fn from(value: enterRedemptionQueueViaSfrxEthReturn) -> Self {
                    (value._nftId,)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>>
            for enterRedemptionQueueViaSfrxEthReturn {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self { _nftId: tuple.0 }
                }
            }
        }
        #[automatically_derived]
        impl alloy_sol_types::SolCall for enterRedemptionQueueViaSfrxEthCall {
            type Parameters<'a> = (
                alloy::sol_types::sol_data::Address,
                alloy::sol_types::sol_data::Uint<120>,
            );
            type Token<'a> = <Self::Parameters<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            type Return = alloy::sol_types::private::primitives::aliases::U256;
            type ReturnTuple<'a> = (alloy::sol_types::sol_data::Uint<256>,);
            type ReturnToken<'a> = <Self::ReturnTuple<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            const SIGNATURE: &'static str = "enterRedemptionQueueViaSfrxEth(address,uint120)";
            const SELECTOR: [u8; 4] = [225u8, 76u8, 187u8, 138u8];
            #[inline]
            fn new<'a>(
                tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType,
            ) -> Self {
                tuple.into()
            }
            #[inline]
            fn tokenize(&self) -> Self::Token<'_> {
                (
                    <alloy::sol_types::sol_data::Address as alloy_sol_types::SolType>::tokenize(
                        &self._recipient,
                    ),
                    <alloy::sol_types::sol_data::Uint<
                        120,
                    > as alloy_sol_types::SolType>::tokenize(&self._sfrxEthAmount),
                )
            }
            #[inline]
            fn tokenize_returns(ret: &Self::Return) -> Self::ReturnToken<'_> {
                (
                    <alloy::sol_types::sol_data::Uint<
                        256,
                    > as alloy_sol_types::SolType>::tokenize(ret),
                )
            }
            #[inline]
            fn abi_decode_returns(data: &[u8]) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence(data)
                    .map(|r| {
                        let r: enterRedemptionQueueViaSfrxEthReturn = r.into();
                        r._nftId
                    })
            }
            #[inline]
            fn abi_decode_returns_validate(
                data: &[u8],
            ) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence_validate(data)
                    .map(|r| {
                        let r: enterRedemptionQueueViaSfrxEthReturn = r.into();
                        r._nftId
                    })
            }
        }
    };
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    /**Function with signature `redemptionQueueState()` and selector `0x1494ef63`.
```solidity
function redemptionQueueState() external view returns (uint64 nextNftId, uint64 queueLengthSecs, uint64 redemptionFee, uint64 earlyExitFee);
```*/
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct redemptionQueueStateCall;
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    ///Container type for the return parameters of the [`redemptionQueueState()`](redemptionQueueStateCall) function.
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct redemptionQueueStateReturn {
        #[allow(missing_docs)]
        pub nextNftId: u64,
        #[allow(missing_docs)]
        pub queueLengthSecs: u64,
        #[allow(missing_docs)]
        pub redemptionFee: u64,
        #[allow(missing_docs)]
        pub earlyExitFee: u64,
    }
    #[allow(
        non_camel_case_types,
        non_snake_case,
        clippy::pub_underscore_fields,
        clippy::style
    )]
    const _: () = {
        use alloy::sol_types as alloy_sol_types;
        {
            #[doc(hidden)]
            #[allow(dead_code)]
            type UnderlyingSolTuple<'a> = ();
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = ();
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<redemptionQueueStateCall>
            for UnderlyingRustTuple<'_> {
                fn from(value: redemptionQueueStateCall) -> Self {
                    ()
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>>
            for redemptionQueueStateCall {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self
                }
            }
        }
        {
            #[doc(hidden)]
            #[allow(dead_code)]
            type UnderlyingSolTuple<'a> = (
                alloy::sol_types::sol_data::Uint<64>,
                alloy::sol_types::sol_data::Uint<64>,
                alloy::sol_types::sol_data::Uint<64>,
                alloy::sol_types::sol_data::Uint<64>,
            );
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (u64, u64, u64, u64);
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<redemptionQueueStateReturn>
            for UnderlyingRustTuple<'_> {
                fn from(value: redemptionQueueStateReturn) -> Self {
                    (
                        value.nextNftId,
                        value.queueLengthSecs,
                        value.redemptionFee,
                        value.earlyExitFee,
                    )
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>>
            for redemptionQueueStateReturn {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self {
                        nextNftId: tuple.0,
                        queueLengthSecs: tuple.1,
                        redemptionFee: tuple.2,
                        earlyExitFee: tuple.3,
                    }
                }
            }
        }
        impl redemptionQueueStateReturn {
            fn _tokenize(
                &self,
            ) -> <redemptionQueueStateCall as alloy_sol_types::SolCall>::ReturnToken<
                '_,
            > {
                (
                    <alloy::sol_types::sol_data::Uint<
                        64,
                    > as alloy_sol_types::SolType>::tokenize(&self.nextNftId),
                    <alloy::sol_types::sol_data::Uint<
                        64,
                    > as alloy_sol_types::SolType>::tokenize(&self.queueLengthSecs),
                    <alloy::sol_types::sol_data::Uint<
                        64,
                    > as alloy_sol_types::SolType>::tokenize(&self.redemptionFee),
                    <alloy::sol_types::sol_data::Uint<
                        64,
                    > as alloy_sol_types::SolType>::tokenize(&self.earlyExitFee),
                )
            }
        }
        #[automatically_derived]
        impl alloy_sol_types::SolCall for redemptionQueueStateCall {
            type Parameters<'a> = ();
            type Token<'a> = <Self::Parameters<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            type Return = redemptionQueueStateReturn;
            type ReturnTuple<'a> = (
                alloy::sol_types::sol_data::Uint<64>,
                alloy::sol_types::sol_data::Uint<64>,
                alloy::sol_types::sol_data::Uint<64>,
                alloy::sol_types::sol_data::Uint<64>,
            );
            type ReturnToken<'a> = <Self::ReturnTuple<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            const SIGNATURE: &'static str = "redemptionQueueState()";
            const SELECTOR: [u8; 4] = [20u8, 148u8, 239u8, 99u8];
            #[inline]
            fn new<'a>(
                tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType,
            ) -> Self {
                tuple.into()
            }
            #[inline]
            fn tokenize(&self) -> Self::Token<'_> {
                ()
            }
            #[inline]
            fn tokenize_returns(ret: &Self::Return) -> Self::ReturnToken<'_> {
                redemptionQueueStateReturn::_tokenize(ret)
            }
            #[inline]
            fn abi_decode_returns(data: &[u8]) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence(data)
                    .map(Into::into)
            }
            #[inline]
            fn abi_decode_returns_validate(
                data: &[u8],
            ) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence_validate(data)
                    .map(Into::into)
            }
        }
    };
    ///Container for all the [`IFraxEtherRedemptionQueue`](self) function calls.
    #[derive(Clone)]
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive()]
    pub enum IFraxEtherRedemptionQueueCalls {
        #[allow(missing_docs)]
        burnRedemptionTicketNft(burnRedemptionTicketNftCall),
        #[allow(missing_docs)]
        enterRedemptionQueueViaSfrxEth(enterRedemptionQueueViaSfrxEthCall),
        #[allow(missing_docs)]
        redemptionQueueState(redemptionQueueStateCall),
    }
    impl IFraxEtherRedemptionQueueCalls {
        /// All the selectors of this enum.
        ///
        /// Note that the selectors might not be in the same order as the variants.
        /// No guarantees are made about the order of the selectors.
        ///
        /// Prefer using `SolInterface` methods instead.
        pub const SELECTORS: &'static [[u8; 4usize]] = &[
            [10u8, 83u8, 52u8, 229u8],
            [20u8, 148u8, 239u8, 99u8],
            [225u8, 76u8, 187u8, 138u8],
        ];
        /// The names of the variants in the same order as `SELECTORS`.
        pub const VARIANT_NAMES: &'static [&'static str] = &[
            ::core::stringify!(burnRedemptionTicketNft),
            ::core::stringify!(redemptionQueueState),
            ::core::stringify!(enterRedemptionQueueViaSfrxEth),
        ];
        /// The signatures in the same order as `SELECTORS`.
        pub const SIGNATURES: &'static [&'static str] = &[
            <burnRedemptionTicketNftCall as alloy_sol_types::SolCall>::SIGNATURE,
            <redemptionQueueStateCall as alloy_sol_types::SolCall>::SIGNATURE,
            <enterRedemptionQueueViaSfrxEthCall as alloy_sol_types::SolCall>::SIGNATURE,
        ];
        /// Returns the signature for the given selector, if known.
        #[inline]
        pub fn signature_by_selector(
            selector: [u8; 4usize],
        ) -> ::core::option::Option<&'static str> {
            match Self::SELECTORS.binary_search(&selector) {
                ::core::result::Result::Ok(idx) => {
                    ::core::option::Option::Some(Self::SIGNATURES[idx])
                }
                ::core::result::Result::Err(_) => ::core::option::Option::None,
            }
        }
        /// Returns the enum variant name for the given selector, if known.
        #[inline]
        pub fn name_by_selector(
            selector: [u8; 4usize],
        ) -> ::core::option::Option<&'static str> {
            let sig = Self::signature_by_selector(selector)?;
            sig.split_once('(').map(|(name, _)| name)
        }
    }
    #[automatically_derived]
    impl alloy_sol_types::SolInterface for IFraxEtherRedemptionQueueCalls {
        const NAME: &'static str = "IFraxEtherRedemptionQueueCalls";
        const MIN_DATA_LENGTH: usize = 0usize;
        const COUNT: usize = 3usize;
        #[inline]
        fn selector(&self) -> [u8; 4] {
            match self {
                Self::burnRedemptionTicketNft(_) => {
                    <burnRedemptionTicketNftCall as alloy_sol_types::SolCall>::SELECTOR
                }
                Self::enterRedemptionQueueViaSfrxEth(_) => {
                    <enterRedemptionQueueViaSfrxEthCall as alloy_sol_types::SolCall>::SELECTOR
                }
                Self::redemptionQueueState(_) => {
                    <redemptionQueueStateCall as alloy_sol_types::SolCall>::SELECTOR
                }
            }
        }
        #[inline]
        fn selector_at(i: usize) -> ::core::option::Option<[u8; 4]> {
            Self::SELECTORS.get(i).copied()
        }
        #[inline]
        fn valid_selector(selector: [u8; 4]) -> bool {
            Self::SELECTORS.binary_search(&selector).is_ok()
        }
        #[inline]
        #[allow(non_snake_case)]
        fn abi_decode_raw(
            selector: [u8; 4],
            data: &[u8],
        ) -> alloy_sol_types::Result<Self> {
            static DECODE_SHIMS: &[fn(
                &[u8],
            ) -> alloy_sol_types::Result<IFraxEtherRedemptionQueueCalls>] = &[
                {
                    fn burnRedemptionTicketNft(
                        data: &[u8],
                    ) -> alloy_sol_types::Result<IFraxEtherRedemptionQueueCalls> {
                        <burnRedemptionTicketNftCall as alloy_sol_types::SolCall>::abi_decode_raw(
                                data,
                            )
                            .map(IFraxEtherRedemptionQueueCalls::burnRedemptionTicketNft)
                    }
                    burnRedemptionTicketNft
                },
                {
                    fn redemptionQueueState(
                        data: &[u8],
                    ) -> alloy_sol_types::Result<IFraxEtherRedemptionQueueCalls> {
                        <redemptionQueueStateCall as alloy_sol_types::SolCall>::abi_decode_raw(
                                data,
                            )
                            .map(IFraxEtherRedemptionQueueCalls::redemptionQueueState)
                    }
                    redemptionQueueState
                },
                {
                    fn enterRedemptionQueueViaSfrxEth(
                        data: &[u8],
                    ) -> alloy_sol_types::Result<IFraxEtherRedemptionQueueCalls> {
                        <enterRedemptionQueueViaSfrxEthCall as alloy_sol_types::SolCall>::abi_decode_raw(
                                data,
                            )
                            .map(
                                IFraxEtherRedemptionQueueCalls::enterRedemptionQueueViaSfrxEth,
                            )
                    }
                    enterRedemptionQueueViaSfrxEth
                },
            ];
            let Ok(idx) = Self::SELECTORS.binary_search(&selector) else {
                return Err(
                    alloy_sol_types::Error::unknown_selector(
                        <Self as alloy_sol_types::SolInterface>::NAME,
                        selector,
                    ),
                );
            };
            DECODE_SHIMS[idx](data)
        }
        #[inline]
        #[allow(non_snake_case)]
        fn abi_decode_raw_validate(
            selector: [u8; 4],
            data: &[u8],
        ) -> alloy_sol_types::Result<Self> {
            static DECODE_VALIDATE_SHIMS: &[fn(
                &[u8],
            ) -> alloy_sol_types::Result<IFraxEtherRedemptionQueueCalls>] = &[
                {
                    fn burnRedemptionTicketNft(
                        data: &[u8],
                    ) -> alloy_sol_types::Result<IFraxEtherRedemptionQueueCalls> {
                        <burnRedemptionTicketNftCall as alloy_sol_types::SolCall>::abi_decode_raw_validate(
                                data,
                            )
                            .map(IFraxEtherRedemptionQueueCalls::burnRedemptionTicketNft)
                    }
                    burnRedemptionTicketNft
                },
                {
                    fn redemptionQueueState(
                        data: &[u8],
                    ) -> alloy_sol_types::Result<IFraxEtherRedemptionQueueCalls> {
                        <redemptionQueueStateCall as alloy_sol_types::SolCall>::abi_decode_raw_validate(
                                data,
                            )
                            .map(IFraxEtherRedemptionQueueCalls::redemptionQueueState)
                    }
                    redemptionQueueState
                },
                {
                    fn enterRedemptionQueueViaSfrxEth(
                        data: &[u8],
                    ) -> alloy_sol_types::Result<IFraxEtherRedemptionQueueCalls> {
                        <enterRedemptionQueueViaSfrxEthCall as alloy_sol_types::SolCall>::abi_decode_raw_validate(
                                data,
                            )
                            .map(
                                IFraxEtherRedemptionQueueCalls::enterRedemptionQueueViaSfrxEth,
                            )
                    }
                    enterRedemptionQueueViaSfrxEth
                },
            ];
            let Ok(idx) = Self::SELECTORS.binary_search(&selector) else {
                return Err(
                    alloy_sol_types::Error::unknown_selector(
                        <Self as alloy_sol_types::SolInterface>::NAME,
                        selector,
                    ),
                );
            };
            DECODE_VALIDATE_SHIMS[idx](data)
        }
        #[inline]
        fn abi_encoded_size(&self) -> usize {
            match self {
                Self::burnRedemptionTicketNft(inner) => {
                    <burnRedemptionTicketNftCall as alloy_sol_types::SolCall>::abi_encoded_size(
                        inner,
                    )
                }
                Self::enterRedemptionQueueViaSfrxEth(inner) => {
                    <enterRedemptionQueueViaSfrxEthCall as alloy_sol_types::SolCall>::abi_encoded_size(
                        inner,
                    )
                }
                Self::redemptionQueueState(inner) => {
                    <redemptionQueueStateCall as alloy_sol_types::SolCall>::abi_encoded_size(
                        inner,
                    )
                }
            }
        }
        #[inline]
        fn abi_encode_raw(&self, out: &mut alloy_sol_types::private::Vec<u8>) {
            match self {
                Self::burnRedemptionTicketNft(inner) => {
                    <burnRedemptionTicketNftCall as alloy_sol_types::SolCall>::abi_encode_raw(
                        inner,
                        out,
                    )
                }
                Self::enterRedemptionQueueViaSfrxEth(inner) => {
                    <enterRedemptionQueueViaSfrxEthCall as alloy_sol_types::SolCall>::abi_encode_raw(
                        inner,
                        out,
                    )
                }
                Self::redemptionQueueState(inner) => {
                    <redemptionQueueStateCall as alloy_sol_types::SolCall>::abi_encode_raw(
                        inner,
                        out,
                    )
                }
            }
        }
    }
    use alloy::contract as alloy_contract;
    /**Creates a new wrapper around an on-chain [`IFraxEtherRedemptionQueue`](self) contract instance.

See the [wrapper's documentation](`IFraxEtherRedemptionQueueInstance`) for more details.*/
    #[inline]
    pub const fn new<
        P: alloy_contract::private::Provider<N>,
        N: alloy_contract::private::Network,
    >(
        address: alloy_sol_types::private::Address,
        __provider: P,
    ) -> IFraxEtherRedemptionQueueInstance<P, N> {
        IFraxEtherRedemptionQueueInstance::<P, N>::new(address, __provider)
    }
    /**A [`IFraxEtherRedemptionQueue`](self) instance.

Contains type-safe methods for interacting with an on-chain instance of the
[`IFraxEtherRedemptionQueue`](self) contract located at a given `address`, using a given
provider `P`.

If the contract bytecode is available (see the [`sol!`](alloy_sol_types::sol!)
documentation on how to provide it), the `deploy` and `deploy_builder` methods can
be used to deploy a new instance of the contract.

See the [module-level documentation](self) for all the available methods.*/
    #[derive(Clone)]
    pub struct IFraxEtherRedemptionQueueInstance<
        P,
        N = alloy_contract::private::Ethereum,
    > {
        address: alloy_sol_types::private::Address,
        provider: P,
        _network: ::core::marker::PhantomData<N>,
    }
    #[automatically_derived]
    impl<P, N> ::core::fmt::Debug for IFraxEtherRedemptionQueueInstance<P, N> {
        #[inline]
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_tuple("IFraxEtherRedemptionQueueInstance")
                .field(&self.address)
                .finish()
        }
    }
    /// Instantiation and getters/setters.
    impl<
        P: alloy_contract::private::Provider<N>,
        N: alloy_contract::private::Network,
    > IFraxEtherRedemptionQueueInstance<P, N> {
        /**Creates a new wrapper around an on-chain [`IFraxEtherRedemptionQueue`](self) contract instance.

See the [wrapper's documentation](`IFraxEtherRedemptionQueueInstance`) for more details.*/
        #[inline]
        pub const fn new(
            address: alloy_sol_types::private::Address,
            __provider: P,
        ) -> Self {
            Self {
                address,
                provider: __provider,
                _network: ::core::marker::PhantomData,
            }
        }
        /// Returns a reference to the address.
        #[inline]
        pub const fn address(&self) -> &alloy_sol_types::private::Address {
            &self.address
        }
        /// Sets the address.
        #[inline]
        pub fn set_address(&mut self, address: alloy_sol_types::private::Address) {
            self.address = address;
        }
        /// Sets the address and returns `self`.
        pub fn at(mut self, address: alloy_sol_types::private::Address) -> Self {
            self.set_address(address);
            self
        }
        /// Returns a reference to the provider.
        #[inline]
        pub const fn provider(&self) -> &P {
            &self.provider
        }
    }
    impl<P: ::core::clone::Clone, N> IFraxEtherRedemptionQueueInstance<&P, N> {
        /// Clones the provider and returns a new instance with the cloned provider.
        #[inline]
        pub fn with_cloned_provider(self) -> IFraxEtherRedemptionQueueInstance<P, N> {
            IFraxEtherRedemptionQueueInstance {
                address: self.address,
                provider: ::core::clone::Clone::clone(&self.provider),
                _network: ::core::marker::PhantomData,
            }
        }
    }
    /// Function calls.
    impl<
        P: alloy_contract::private::Provider<N>,
        N: alloy_contract::private::Network,
    > IFraxEtherRedemptionQueueInstance<P, N> {
        /// Creates a new call builder using this contract instance's provider and address.
        ///
        /// Note that the call can be any function call, not just those defined in this
        /// contract. Prefer using the other methods for building type-safe contract calls.
        pub fn call_builder<C: alloy_sol_types::SolCall>(
            &self,
            call: &C,
        ) -> alloy_contract::SolCallBuilder<&P, C, N> {
            alloy_contract::SolCallBuilder::new_sol(&self.provider, &self.address, call)
        }
        ///Creates a new call builder for the [`burnRedemptionTicketNft`] function.
        pub fn burnRedemptionTicketNft(
            &self,
            _nftId: alloy::sol_types::private::primitives::aliases::U256,
            _recipient: alloy::sol_types::private::Address,
        ) -> alloy_contract::SolCallBuilder<&P, burnRedemptionTicketNftCall, N> {
            self.call_builder(
                &burnRedemptionTicketNftCall {
                    _nftId,
                    _recipient,
                },
            )
        }
        ///Creates a new call builder for the [`enterRedemptionQueueViaSfrxEth`] function.
        pub fn enterRedemptionQueueViaSfrxEth(
            &self,
            _recipient: alloy::sol_types::private::Address,
            _sfrxEthAmount: alloy::sol_types::private::primitives::aliases::U120,
        ) -> alloy_contract::SolCallBuilder<&P, enterRedemptionQueueViaSfrxEthCall, N> {
            self.call_builder(
                &enterRedemptionQueueViaSfrxEthCall {
                    _recipient,
                    _sfrxEthAmount,
                },
            )
        }
        ///Creates a new call builder for the [`redemptionQueueState`] function.
        pub fn redemptionQueueState(
            &self,
        ) -> alloy_contract::SolCallBuilder<&P, redemptionQueueStateCall, N> {
            self.call_builder(&redemptionQueueStateCall)
        }
    }
    /// Event filters.
    impl<
        P: alloy_contract::private::Provider<N>,
        N: alloy_contract::private::Network,
    > IFraxEtherRedemptionQueueInstance<P, N> {
        /// Creates a new event filter using this contract instance's provider and address.
        ///
        /// Note that the type can be any event, not just those defined in this contract.
        /// Prefer using the other methods for building type-safe event filters.
        pub fn event_filter<E: alloy_sol_types::SolEvent>(
            &self,
        ) -> alloy_contract::Event<&P, E, N> {
            alloy_contract::Event::new_sol(&self.provider, &self.address)
        }
    }
}
